#!/usr/bin/bash
shopt -s nullglob
set -eu

KVER=$(uname -r)
MODULES_DIR="/usr/lib/modules"

stash() {
	local target
	while read -r target; do
		if [[ "/$target" == "$MODULES_DIR/$KVER/vmlinuz" ]]; then
			echo "==> Stashing kernel modules: $KVER"
			cp -rlx "$MODULES_DIR/$KVER" -T "$MODULES_DIR/.$KVER"
			chattr +d "$MODULES_DIR/.$KVER"
		fi
	done
}

restore() {
	local target

	if [[ -d "$MODULES_DIR/.$KVER" ]]; then
		echo "==> Restore kernel modules: $KVER"
		rm -rf "$MODULES_DIR/$KVER"
		mv -T "$MODULES_DIR/.$KVER" "$MODULES_DIR/$KVER"
	fi

}

wipe() {
	local target
	for target in "$MODULES_DIR"/.* "$MODULES_DIR"/*; do
		if [[ -d "$target" && "${target##*/}" != "$KVER" && $(lsattr -d "$target") =~ ^[-[:alpha:]]*d ]]; then
			rm -rf "$target"
		fi
	done
}

usage() {
	echo "usage: ${0##*/} <stash|restore|wipe|usage>"
}

case ${1:-} in
	stash|restore|wipe|usage) $1 ;;

	*) usage >&2 ; exit 1 ;;
esac
