#!/usr/bin/bash
shopt -s nullglob
set -eu

KVER=$(uname -r)
MDIR="/usr/lib/modules"

stash() {
	local target
	while read -r target; do
		if [[ "/$target" == "$MDIR/$KVER/vmlinuz" ]]; then
			echo "==> Stashing kernel modules: $KVER"
			install -d "$MDIR/.$KVER"
			chattr +d "$MDIR/.$KVER"
			cp -alut "$MDIR/.$KVER" "$MDIR/$KVER"/*
		fi
	done
}

restore() {
	local target

	if [[ -d "$MDIR/.$KVER" ]]; then
		echo "==> Restore kernel modules: $KVER"
		install -d "$MDIR/$KVER"
		chattr +d "$MDIR/$KVER"
		cp -alut "$MDIR/$KVER" "$MDIR/.$KVER"/*
		rm -r "$MDIR/.$KVER"
	fi

}

wipe() {
	local target
	for target in "$MDIR"/.* "$MDIR"/*; do
		if [[ -d "$target" && "${target##*/}" != "$KVER" && $(lsattr -d "$target") =~ ^[-[:alpha:]]*d ]]; then
			rm -rf "$target"
		fi
	done
}

usage() {
	echo "usage: ${0##*/} <stash|restore|wipe|usage>"
}

case ${1:-} in
	stash|restore|wipe|usage) $1 ;;

	*) usage >&2 ; exit 1 ;;
esac
